formatter: "markdown"

version: ""

header-from: ""
footer-from: ""

recursive:
  enabled: false
  path: modules
  include-main: true

sections:
  hide: []
  show: []

  hide-all: false # deprecated in v0.13.0, removed in v0.15.0
  show-all: true  # deprecated in v0.13.0, removed in v0.15.0

content: |-
  {{ .Header }}
  ## Setup
  To use this module you will need
  * Terraform
  * Some form of Google authorization
  * A project already created
  * Authorization for Cloud Run in the project
   ## Usage
  The defaults will provision a publicly available simple webpage container (us-docker.pkg.dev/cloudrun/container/hello), and can be invoked as simple as replacing YOUR-PROJECT-NAME-HERE:
  ```hcl
  module "main" {
  source = "github.com/akettmann/gcp_serverless_webapp"
  }
  provider "google" {
    project = "YOUR-PROJECT-NAME-HERE"
  }
  output "url" {
    value = module.main.cloud_run_url
  }
  ```
  The main settings you are likely to want, with defaults:

  ```hcl
  module "main" {
    source = "github.com/akettmann/gcp_serverless_webapp"
  {{- $skipList := list "startup_cpu_boost" "deployment_name" "cpu_only_during_requests" "labels" "publicly_visible" "min_instances" "max_instances" }}
  {{- range .Module.Inputs }}
    {{- if not (has .Name $skipList) }}
    # {{ .Description }}
    {{ .Name }} = {{ .GetValue }}
    {{- end }}
  {{- end }}
  }
  output "url" {
    value = module.main.cloud_run_url
  }
  ```

  Passing the output from the module at module_name.cloud_run_url outwards will give you the URL to access your service.
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: false
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
